name: Daily Spoof Commits

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 4 * * *"
    - cron: "0 9 * * *"
    - cron: "0 14 * * *"
    - cron: "0 20 * * *"
  workflow_dispatch:


jobs:
  spoof-commits:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Git
      run: |
        git config user.name "Durveshbaharwal"
        git config user.email "durveshbaharwal@gmail.com"

    - name: Generate 5–20 fake commits with realistic timestamps
      run: |
        FILE="progress_log.txt"
        COUNT=$(( ( RANDOM % 16 ) + 5 ))  # Random number between 5 and 20
        for i in $(seq 1 $COUNT); do
          echo "Fake Commit $i on $(date +'%Y-%m-%d %H:%M:%S') -- $RANDOM" >> $FILE
          git add $FILE
    
          COMMIT_TIME=$(date -d "$((RANDOM % 720)) minutes ago" +"%Y-%m-%dT%H:%M:%S")
    
          GIT_AUTHOR_DATE="$COMMIT_TIME" GIT_COMMITTER_DATE="$COMMIT_TIME" \
          git commit -m "Spoofed commit $i" || echo "No changes to commit for $i"
        done


    - name: Push to repo
      run: git push
